import { Board } from "./models"

export const allBoard: Board = {
  columns: [
    { id: "col-1", title: "Backlog", order: 1 },
    { id: "col-2", title: "À faire", order: 2 },
    { id: "col-3", title: "En cours", order: 3 },
    { id: "col-4", title: "Revue", order: 4 },
    { id: "col-5", title: "Terminé", order: 5 },
  ],
  tickets: [
    {
      id: "ticket-1",
      title: "Créer le modèle de données utilisateur",
      description: "Définir les champs nécessaires pour le profil utilisateur.",
      type: "task",
      assignee: "dev1",
      order: 1,
      columnId: "col-1",
    },
    {
      id: "ticket-2",
      title: "Corriger l'erreur 404 sur la page produit",
      description: "La page produit renvoie une erreur 404 pour certains IDs.",
      type: "bug",
      assignee: "dev2",
      order: 1,
      columnId: "col-2",
    },
    {
      id: "ticket-3",
      title: "Ajouter un filtre par catégorie",
      description: "Permettre aux utilisateurs de filtrer les produits par catégorie.",
      type: "feature",
      assignee: "dev3",
      order: 1,
      columnId: "col-3",
    },
    {
      id: "ticket-4",
      title: "Mettre à jour la documentation API",
      description: "Ajouter les nouveaux endpoints et exemples d'utilisation.",
      type: "task",
      assignee: "dev1",
      order: 2,
      columnId: "col-3",
    },
    {
      id: "ticket-5",
      title: "Tester la compatibilité mobile",
      description: "Vérifier l'affichage et l'interaction sur mobile.",
      type: "task",
      assignee: "dev4",
      order: 1,
      columnId: "col-4",
    },
    {
      id: "ticket-6",
      title: "Optimiser les images pour le web",
      description: "Compresser et redimensionner les images pour un chargement plus rapide.",
      type: "task",
      assignee: "dev2",
      order: 2,
      columnId: "col-2",
    },
    {
      id: "ticket-7",
      title: "Ajouter un système de commentaires",
      description: "Permettre aux utilisateurs de commenter les produits.",
      type: "feature",
      assignee: "dev3",
      order: 2,
      columnId: "col-1",
    },
    {
      id: "ticket-8",
      title: "Corriger le bug de panier vide",
      description: "Le panier reste vide après ajout d'un produit.",
      type: "bug",
      assignee: "dev1",
      order: 3,
      columnId: "col-3",
    },
    {
      id: "ticket-9",
      title: "Déployer la nouvelle version",
      description: "Déployer la version 1.2.0 sur le serveur de production.",
      type: "task",
      assignee: "dev4",
      order: 1,
      columnId: "col-5",
    },
    {
      id: "ticket-10",
      title: "Mettre à jour les dépendances",
      description: "Mettre à jour toutes les dépendances npm pour éviter les vulnérabilités.",
      type: "task",
      assignee: "dev2",
      order: 2,
      columnId: "col-5",
    },
  ],
};
